"""add_processed_count_to_bulk_job

Revision ID: 0938d34e5593
Revises: 0af76f62bb95
Create Date: 2025-12-16 00:25:35.157501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0938d34e5593'
down_revision = '0af76f62bb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_bulk_job', sa.Column('processed_count', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_bulk_job', 'processed_count')
    # ### end Alembic commands ###
